sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:

before_script:
  - npm install -g @angular/cli

script:
  - ng build
  - ng lint
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng e2e --protractor-config=./e2e/protractor-ci.conf.js
